from .page_1 import section_1
from .page_2 import section_2
from .page_3 import section_3
from .page_4 import section_4
from .page_5 import section_5
from .page_6 import section_6
from .page_7 import section_7
from .page_8 import section_8
from .page_9 import section_9
from .page_10 import section_10
